# Generated by Django 3.1 on 2020-10-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nercrisis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='source',
            field=models.CharField(choices=[('File', 'File'), ('Twitter', 'Twitter')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='text',
            field=models.TextField(max_length=2500, null=True),
        ),
    ]
